<x-layout>
    @section('title', 'System KPI Reports')

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4 mb-8 border-b border-gray-200 pb-5">
            <div>
                <h1 class="text-2xl font-bold text-gray-900">System Performance Reports</h1>
                <p class="text-sm text-gray-500 mt-1">Generate and review frozen historical snapshots of system KPIs.</p>
            </div>
            @php
$latestReport = App\Models\AdminReport::latest()->first();
$canGenerate = !$latestReport || $latestReport->created_at->addDays(30)->isPast()
            @endphp

            @if($canGenerate)
                    <button type="button" onclick="openGenerateModal(this)" id="generate-btn" class="bg-brand-blue hover:bg-blue-800 text-white px-6 py-2.5 rounded-lg text-sm font-bold transition shadow-md flex items-center gap-2 pointer">
                        Generate New 30-Day Snapshot Report
                    </button>
            @else
            @php
    $daysLeft = now()->diffInDays($latestReport->created_at->addDays(30));
    $displayDays = $daysLeft > 0 ? $daysLeft : 1;
            @endphp
                <button disabled class="bg-gray-100 border boder-gray-300 text-gray-400 px-6 py-2.5 rounded-lg text-sm font-bold shadow-sm flex items-center gap-2 cursor-not-allowed" title="Cooldown active across all Admins">
                    Global Cooldown Active: Please wait {{ round($displayDays, 0) }} more day(s) before generating a new report.
                </button>
            @endif


        </div>

        <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <div class="overflow-x-auto">
                <table class="w-full text-left border-collapse">
                    <thead>
                        <tr class="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider border-b border-gray-200">
                            <th class="font-bold p-4">Report Title & Period</th>
                            <th class="font-bold p-4">Generated By</th>
                            <th class="font-bold p-4">Generation Date</th>
                            <th class="font-bold p-4 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        @forelse ($reports as $report)
                            <tr class="hover:bg-gray-50 transition group">
                                <td class="p-4">
                                    <div class="flex items-center gap-3">
                                        <div class="w-10 h-10 rounded-lg bg-blue-50 text-brand-blue flex items-center justify-center border border-blue-100 shadow-sm">
                                            <i class="fa-solid fa-chart-line"></i>
                                        </div>
                                        <div>
                                            <div class="font-bold text-gray-900">{{ $report->title }}</div>
                                            <div class="text-xs text-gray-500 mt-0.5">
                                                <i class="fa-regular fa-calendar mr-1"></i> Data: {{ $report->metrics['period'] }}
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="p-4">
                                    <div class="flex items-center gap-2">
                                        <div class="w-6 h-6 rounded-full bg-brand-dark flex items-center justify-center text-white text-[10px] font-bold">
                                            {{ strtoupper(substr($report->generator->user->name, 0, 1)) }}
                                        </div>
                                        <span class="text-sm text-gray-700 font-medium">{{ $report->generator->user->name ?? 'Unknown' }}</span>
                                    </div>
                                </td>
                                <td class="p-4">
                                    <span class="text-sm text-gray-700">{{ $report->created_at->format('M d, Y') }}</span>
                                    <span class="block text-xs text-gray-400">{{ $report->created_at->format('h:i A') }}</span>
                                </td>
                                <td class="p-4 text-right">
                                    <div class="flex items-center justify-end gap-2">
                                        <a href="{{ route('admin.reports.export_pdf', $report->id) }}" class="inline-flex items-center gap-2 bg-white hover:bg-gray-50 border border-gray-200 text-gray-700 px-3 py-1.5 rounded-lg text-sm font-bold transition shadow-sm">
                                            <i class="fa-solid fa-file-pdf"></i> Download PDF
                                        </a>

                                        <a href="{{ route('admin.reports.show', $report->id) }}" class="inline-flex items-center gap-2 bg-white hover:bg-gray-50 border border-gray-200 text-gray-700 px-3 py-1.5 rounded-lg text-sm font-bold transition shadow-sm">
                                            View Details <i class="fa-solid fa-arrow-right text-xs"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4" class="p-12 text-center text-gray-500">
                                    <div class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gray-50 border-2 border-dashed border-gray-200 mb-4">
                                        <i class="fa-solid fa-chart-pie text-2xl text-gray-300"></i>
                                    </div>
                                    <p class="text-lg font-bold text-gray-900">No Reports Generated Yet</p>
                                    <p class="text-sm text-gray-500 max-w-sm mx-auto mt-1">Click the "Generate New Snapshot" button above to crunch the numbers and create your first performance report.</p>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            @if($reports->hasPages())
                <div class="px-6 py-4 border-t border-gray-200 bg-gray-50">
                    {{ $reports->links() }}
                </div>
            @endif
        </div>
    </div>
    <div id="generate-modal" class="fixed inset-0 z-50 hidden items-center justify-center  transition-opacity duration-200">
        <div id="generate-modal-card" class="bg-white rounded-2xl p-6 max-w-sm w-full mx-4 shadow-2xl transform scale-95 transition-transform duration-200">
            <div class="text-center">
                <div class="mx-auto flex items-center justify-center h-14 w-14 rounded-full bg-yellow-100 mb-4">
                    <i class="fa-solid fa-triangle-exclamation text-yellow-600 text-2xl"></i>
                </div>

                <h3 class="text-xl font-bold text-gray-900 mb-2">Confirm Generation</h3>

                <p class="text-sm text-gray-500 mb-6">
                    Are you sure you want to generate this report <span id="generate-items-name" class="font-bold text-gray-900 px-1 py-0.5 bg-gray-100 rounded"></span>? This action can't be undone.
                </p>

                <div class="flex justify-center gap-3">
                    <button type="button" onclick="closeGenerateModal()" class="px-5 py-2.5 bg-gray-100 text-gray-700 hover:bg-gray-200 font-bold rounded-xl transition duration-150 pointer">
                        Cancel
                    </button>
                    <form action="{{ route('admin.reports.generate') }}" method="POST">
                    @csrf
                    <button type="submit" id="confirm-generate-btn" class="px-5 py-2.5 bg-yellow-600 text-white hover:bg-yellow-700 font-bold rounded-xl transition duration-150 shadow-sm shadow-yellow-200 pointer">
                        Yes, Generate
                    </button>
                </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        let formToSubmitId = null;
        function openGenerateModal(buttonElement) {
            formToSubmitId = buttonElement.getAttribute('data-form-id');
            const itemName = buttonElement.getAttribute('data-item-name');
            document.getElementById('generate-items-name').innerText = itemName;

            const modal = document.getElementById('generate-modal');
            const modalCard = document.getElementById('generate-modal-card');

            modal.classList.add('flex');
            modal.classList.remove('hidden');

            setTimeout(() => {
                modalCard.classList.remove('scale-95');
                modalCard.classList.add('scale-100');
            }, 10);
        }
        function closeGenerateModal() {
            const modal = document.getElementById('generate-modal');
            const modalCard = document.getElementById('generate-modal-card');

            modalCard.classList.remove('scale-100');
            modalCard.classList.add('scale-95');

            setTimeout(() => {
                modal.classList.add('hidden');
                modal.classList.remove('flex');
                formToSubmitId = null;
            }, 200);
        }
        document.getElementById('confirm-generate-btn').addEventListener('click', function () {
            if (formToSubmitId) {
                document.getElementById(formToSubmitId).submit();
            }
        });
        document.getElementById('generate-modal').addEventListener('click', function (e) {
            if (e.target === this) {
                closeGenerateModal();
            }
        });
    </script>
</x-layout>
